runtime: python37

handlers:
- url: /api/.*
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /(.*\..*)
  secure: always
  redirect_http_response_code: 301
  static_files: frontend/dist/frontend/\1
  upload: frontend/dist/frontend/.*

- url: /.*
  static_files: frontend/dist/frontend/index.html
  upload: frontend/dist/frontend/index.html
  secure: always
  redirect_http_response_code: 301
