runtime: python37

handlers:
- url: /api/.*
  script: auto
- url: /
  static_files: frontend/dist/frontend/index.html
  upload: frontend/dist/frontend/index.html
- url: /
  static_dir: frontend/dist/frontend

