runtime: python37
api_version: 1

handlers:
- url: /api/*
  script: main.app
- url: /
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html
- url: /
  static_dir: frontend/dist

