runtime: python37

handlers:
- url: /api/.*
  script: auto
  secure: always
- url: /
  static_files: frontend/dist/frontend/index.html
  upload: frontend/dist/frontend/index.html
  secure: always
- url: /
  static_dir: frontend/dist/frontend
  secure: always

